/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author pablo
 */
public class JPanelMonitor extends javax.swing.JPanel {

    /**
     * Creates new form JPanelVista
     */
    public JPanelMonitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMonitor = new javax.swing.JTable();
        jAltaMonitor = new javax.swing.JButton();
        jBajaMonitor = new javax.swing.JButton();
        jActualizarMonitor = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(659, 326));

        jTableMonitor.setBackground(new java.awt.Color(255, 255, 255));
        jTableMonitor.setForeground(new java.awt.Color(0, 0, 0));
        jTableMonitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMonitor);

        jAltaMonitor.setBackground(new java.awt.Color(204, 153, 0));
        jAltaMonitor.setForeground(new java.awt.Color(255, 255, 255));
        jAltaMonitor.setText("Alta Monitor");

        jBajaMonitor.setBackground(new java.awt.Color(204, 153, 0));
        jBajaMonitor.setForeground(new java.awt.Color(255, 255, 255));
        jBajaMonitor.setText("Baja Monitor");

        jActualizarMonitor.setBackground(new java.awt.Color(204, 153, 0));
        jActualizarMonitor.setForeground(new java.awt.Color(255, 255, 255));
        jActualizarMonitor.setText("Actualizar Monitor");
        jActualizarMonitor.setActionCommand("Actualizacion Monitor");

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(204, 153, 0));
        label1.setText("GESTIÓN DE MONITORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jAltaMonitor)
                                .addGap(18, 18, 18)
                                .addComponent(jBajaMonitor)
                                .addGap(18, 18, 18)
                                .addComponent(jActualizarMonitor))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 255, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAltaMonitor)
                    .addComponent(jBajaMonitor)
                    .addComponent(jActualizarMonitor))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jActualizarMonitor;
    public javax.swing.JButton jAltaMonitor;
    public javax.swing.JButton jBajaMonitor;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMonitor;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
