
package Vista;

/**
 *
 * @author Usuario
 */
public class VistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form vistaLogin
     */
    public VistaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        BotonConectar = new javax.swing.JButton();
        BotonSalirEleccion = new javax.swing.JButton();
        EleccionServidor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TextoServidor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso a la aplicación");

        Panel1.setBackground(new java.awt.Color(204, 204, 204));
        Panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel1.setToolTipText("");
        Panel1.setName(""); // NOI18N

        BotonConectar.setBackground(new java.awt.Color(204, 153, 0));
        BotonConectar.setFont(new java.awt.Font("Arial Nova", 0, 12)); // NOI18N
        BotonConectar.setForeground(new java.awt.Color(255, 255, 255));
        BotonConectar.setText("Conectar");

        BotonSalirEleccion.setFont(new java.awt.Font("Arial Nova", 0, 12)); // NOI18N
        BotonSalirEleccion.setText("Salir");
        BotonSalirEleccion.setActionCommand("SalirDialogoConexion");

        EleccionServidor.setBackground(new java.awt.Color(255, 255, 255));
        EleccionServidor.setFont(new java.awt.Font("Arial Nova", 0, 12)); // NOI18N
        EleccionServidor.setForeground(new java.awt.Color(0, 0, 0));
        EleccionServidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MariaBD", "Oracle" }));
        EleccionServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleccionServidorActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gymmmm.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        TextoServidor.setFont(new java.awt.Font("Arial Nova", 0, 12)); // NOI18N
        TextoServidor.setForeground(new java.awt.Color(0, 0, 0));
        TextoServidor.setText("Servidor:");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TextoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EleccionServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(BotonConectar)
                                .addGap(18, 18, 18)
                                .addComponent(BotonSalirEleccion)))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EleccionServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonConectar)
                    .addComponent(BotonSalirEleccion))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(Panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EleccionServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleccionServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EleccionServidorActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonConectar;
    public javax.swing.JButton BotonSalirEleccion;
    public javax.swing.JComboBox<String> EleccionServidor;
    public javax.swing.JPanel Panel1;
    public javax.swing.JLabel TextoServidor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
