/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author pablo
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaFrame
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBarra1 = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();
        PágPrincipal = new javax.swing.JMenuItem();
        jMenuMonitores = new javax.swing.JMenu();
        jMenuGestionMonitores = new javax.swing.JMenuItem();
        jMenuSocios = new javax.swing.JMenu();
        jMenuGestionSocios = new javax.swing.JMenuItem();
        jMenuActividades = new javax.swing.JMenu();
        jMenuGestionActividades = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuSalirAplicacion = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión del Gimnasio");

        jMenuBarra1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBarra1.setForeground(new java.awt.Color(0, 0, 0));

        Home.setText("Home");

        PágPrincipal.setForeground(new java.awt.Color(204, 153, 0));
        PágPrincipal.setText("Pág. Principal");
        Home.add(PágPrincipal);

        jMenuBarra1.add(Home);

        jMenuMonitores.setForeground(new java.awt.Color(255, 255, 255));
        jMenuMonitores.setText("Monitores");

        jMenuGestionMonitores.setBackground(new java.awt.Color(204, 153, 0));
        jMenuGestionMonitores.setForeground(new java.awt.Color(204, 153, 0));
        jMenuGestionMonitores.setText("Gestión de Monitores");
        jMenuGestionMonitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionMonitoresActionPerformed(evt);
            }
        });
        jMenuMonitores.add(jMenuGestionMonitores);

        jMenuBarra1.add(jMenuMonitores);

        jMenuSocios.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSocios.setText("Socios");

        jMenuGestionSocios.setForeground(new java.awt.Color(204, 153, 0));
        jMenuGestionSocios.setText("Gestión de Socios");
        jMenuGestionSocios.setToolTipText("");
        jMenuGestionSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionSociosActionPerformed(evt);
            }
        });
        jMenuSocios.add(jMenuGestionSocios);

        jMenuBarra1.add(jMenuSocios);

        jMenuActividades.setForeground(new java.awt.Color(255, 255, 255));
        jMenuActividades.setText("Actividades");

        jMenuGestionActividades.setForeground(new java.awt.Color(204, 153, 0));
        jMenuGestionActividades.setText("Gestión de Actividades");
        jMenuActividades.add(jMenuGestionActividades);

        jMenuBarra1.add(jMenuActividades);

        jMenuSalir.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSalir.setText("Salir");

        jMenuSalirAplicacion.setBackground(new java.awt.Color(204, 153, 0));
        jMenuSalirAplicacion.setForeground(new java.awt.Color(204, 153, 0));
        jMenuSalirAplicacion.setText("Salir de la aplicación");
        jMenuSalir.add(jMenuSalirAplicacion);

        jMenuBarra1.add(jMenuSalir);

        setJMenuBar(jMenuBarra1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuGestionMonitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionMonitoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuGestionMonitoresActionPerformed

    private void jMenuGestionSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuGestionSociosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Home;
    public javax.swing.JMenuItem PágPrincipal;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenuActividades;
    public javax.swing.JMenuBar jMenuBarra1;
    public javax.swing.JMenuItem jMenuGestionActividades;
    public javax.swing.JMenuItem jMenuGestionMonitores;
    public javax.swing.JMenuItem jMenuGestionSocios;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenu jMenuMonitores;
    public javax.swing.JMenu jMenuSalir;
    public javax.swing.JMenuItem jMenuSalirAplicacion;
    public javax.swing.JMenu jMenuSocios;
    // End of variables declaration//GEN-END:variables
}
